#!/usr/bin/env bash
# Usage: ./0-world_wide_web <domain> [subdomain]
# Display information about subdomains.

domain_information() {
    local subdomain="$2"
    local domain="$1"

    if [ -n "$subdomain" ]; then
        dig_output=$(dig "$subdomain.$domain" +short)
        record_type=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION/ {getline; print $4}')
        destination=$(echo "$dig_output" | tr -d '\n')
        echo "The subdomain $subdomain is a $record_type record and points to $destination"
    fi
}

if [ "$#" -eq 1 ]; then
    # Display information for default subdomains
    subdomains=("www" "lb-01" "web-01" "web-02")

    for subdomain in "${subdomains[@]}"; do
        domain_information "$1" "$subdomain"
    done
elif [ "$#" -eq 2 ]; then
    # Display information for the specified subdomain
    domain_information "$1" "$2"
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi
