#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> [subdomain]
# Display information about subdomains.

domain_information() {
    local result record_type destination

    result=$(dig "$2.$1" +short)
    record_type=$(dig "$2.$1" | awk '/ANSWER SECTION/ {getline; print $4}')
    destination=$(echo "$result" | tr '\n' ' ')

    echo "The subdomain $2 is a $record_type record and points to $destination"
}

if [ "$#" -eq 1 ]; then
    # Display information for default subdomains
    subdomains=("www" "lb-01" "web-01" "web-02")

    for subdomain in "${subdomains[@]}"; do
        domain_information "$1" "$subdomain"
    done
elif [ "$#" -eq 2 ]; then
    # Display information for the specified subdomain
    domain_information "$1" "$2"
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi
