#!/usr/bin/env bash

# Install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Create a custom Nginx configuration file
echo "add_header X-Served-By \$hostname;" | sudo tee /etc/nginx/conf.d/custom_header

# Restart Nginx to apply the changes
sudo service nginx restart
