#!/usr/bin/env bash
#This Script Performs the following:
#1: displays bad luck for the 4th loop iteration
#2: displays good luck for the 8th loop iteration
#3: displays Best School for the other iterations
n=1;

while [ $n -le 10 ]
do 
if [ $n -eq 4 ]
then
echo "bad luck"
(( ++n ))
elif [ $n -eq 8 ]
then
echo "good luck"
(( ++n ))
else
echo "Best School"
(( ++n ))
fi
done
